### ISSUE TITLE
Not critical issue

### ISSUE THREAD

**Issue by mdmunir** [nenad-zivkovic/yii2-basic-template#1]
Nice work gan :+1: 
- Why use prefix underscore in protected folder. IMO, better using name `protected`. Folder `themes` is also protected but not using prefix underscore.
- Folder `vendor` protected directory. IMO, better put it in root directory.

**Comment by nenad-zivkovic** [comment]
Hello,

Underscore is explained here: http://www.freetuts.org/tutorial/view?id=6#structure

Folder `themes` is not protected, it contain public files, like css.

`Vendor` can contain scripts that should not be executed by users, and therefore should be protected.
