### ISSUE TITLE
How to access GII?

### ISSUE THREAD

**Issue by eduardoarandah** [nenad-zivkovic/yii2-basic-template#2]
When I try route:
http://localhost/myproject/index.php?r=gii
it shows nothing. 

in fact, when doing any invalid route it shows no errors, like this:
http://localhost/myproject/index.php?r=asdfasdf

I have no idea why it doesn't show errors, it is freshly installed, superuser logged in and all other routes work perfect
![sin titulo](https://cloud.githubusercontent.com/assets/4065733/6530486/ecfc9ee0-c3f6-11e4-8117-86bd45deeb82.png)

**Comment by nenad-zivkovic** [comment]
Improved basic and advanced templates come with pretty url configured out of the box, along with htaccess that will remove ugly index.php from your url. Try this: localhost/stadiumreporter/gii

**Comment by eduardoarandah** [comment]
ok thanks!
