### ISSUE TITLE
login additional field

### ISSUE THREAD

**Issue by markquee** [nenad-zivkovic/yii2-basic-template#3]
Hi im newbie here so take it easy on me.
Im adding additional field for the login from (username/password) before to (last_name,first_name,password and username) which means aside from 2 field i want to add addditional 2 fields. How to do it and which part of the code. Thanks..

**Comment by nenad-zivkovic** [comment]
What do you want to do with last_name and first_name in login form ?

**Comment by jtorresig** [comment]
Hi Nenad,
Sorry , but I do not remember to ask you this. Please check the email
address.

Best regards,
Jorge
Em 10/03/2016 14:07, "Nenad Zivkovic" notifications@github.com escreveu:

**Comment by nenad-zivkovic** [comment]
I have no idea what is going on here...

**Comment by markquee** [comment]
Im asking that i want to add also last-name & first_name to add additional comparison in addition to username and password in login form.

**Comment by markquee** [comment]
So in my login form it should have Last_name,first_name,username and password and not just ussername and pword.

**Comment by eduardoarandah** [comment]
@nenad-zivkovic  I think @jtorresig is suscribed to github emails, he thought you wrote him an email.

@markquee modify:
views/site/login.php 
controllers/sitecontroller.php
models/loginform.php
models/useridentity.php
models/user.php

**Comment by nenad-zivkovic** [comment]
@eduardoarandah thanks. That is right
